name = "Elmer"
uuid = "7d1d0d61-b954-47ad-902e-083a93170a02"
version = "0.1.0"
authors = ["gwlagerweij"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Dates = "1.11.0"
Gmsh = "0.3.1"
LinearAlgebra = "1.12.0"
OrderedCollections = "1.8.1"
PhysicalConstants = "0.2.4"
Printf = "1.11.0"
Unitful = "1.24.0"
YAML = "0.4.14"
